"""
Kisan Dost — Hello World Agent Test
===================================
Verifies:
1. Environment loading via python-dotenv.
2. OpenAI Agents SDK initialization & Agent creation.
3. Provider configuration (OpenAI direct, Groq, or Gemini fallback).
4. Tool registration, schema generation, and agent structure.
5. All agents (Triage + 4 specialists) import and structure check.
"""

import os
import sys
from dotenv import load_dotenv

# Step 1: Load environment variables
load_dotenv()

from agents import Agent, function_tool
from agents_setup.provider_config import setup_llm_provider
from tools.crop_advisor import crop_advisor
from context.farmer_context import FarmerProfile


def test_hello_world_agent_setup():
    """Verify that an Agent can be created and configured with tools."""
    print("=" * 60)
    print("KISAN DOST — HELLO WORLD AGENT TEST")
    print("=" * 60)

    # Configure provider
    provider, model = setup_llm_provider()
    print(f"[*] Detected Provider: {provider}")
    print(f"[*] Default Model: {model}")

    @function_tool
    def hello_farmer_tool(farmer_name: str) -> str:
        """A simple test tool that returns a greeting."""
        return f"Assalam-o-Alaikum {farmer_name}! Kisan Dost agent is running successfully."

    # Build basic agent
    hello_agent = Agent(
        name="Hello Kisan Dost",
        instructions="Greet Pakistani farmers warmly in Urdu/English.",
        tools=[hello_farmer_tool, crop_advisor],
    )

    assert hello_agent.name == "Hello Kisan Dost"
    assert len(hello_agent.tools) == 2
    assert hello_farmer_tool.name == "hello_farmer_tool"
    print(f"[+] Basic Agent '{hello_agent.name}' initialized with {len(hello_agent.tools)} tools!")

    # Verify tool schema was auto-generated by the SDK
    print(f"[+] Tool parameters schema generated: {hello_farmer_tool.params_json_schema is not None}")

    # Verify farmer context
    profile = FarmerProfile(name="Ahmad", district="Multan", land_acres=5.0)
    print(f"[+] FarmerProfile context test: {profile.summary()}")
    assert profile.district == "Multan"

    # Verify full multi-agent setup can be imported
    from agents_setup import (
        triage_agent,
        agronomy_agent,
        pest_doctor_agent,
        market_agent,
        finance_agent,
    )

    print(f"[+] Imported Triage Agent: {triage_agent.name} (Handoffs: {len(triage_agent.handoffs)})")
    print(f"[+] Imported Agronomy Agent: {agronomy_agent.name} (Tools: {len(agronomy_agent.tools)})")
    print(f"[+] Imported Pest Doctor Agent: {pest_doctor_agent.name} (Output Guardrails: {len(pest_doctor_agent.output_guardrails)})")
    print(f"[+] Imported Market Agent: {market_agent.name} (Tools: {len(market_agent.tools)})")
    print(f"[+] Imported Finance Agent: {finance_agent.name} (Tools: {len(finance_agent.tools)})")

    print("=" * 60)
    print("ALL HELLO-WORLD SETUP & STRUCTURE CHECKS PASSED!")
    print("=" * 60)
    return True


if __name__ == "__main__":
    success = test_hello_world_agent_setup()
    sys.exit(0 if success else 1)
